name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y stow bats

      - name: Make scripts executable
        run: |
          chmod +x src/manage.sh
          chmod +x src/template.sh

      - name: Run tests
        run: bats test/manage.bats 